name: PlayerSkillsReborn
version: 1.7.4
description: Skills
author: [fatpigsarefat, oRIOn_Tx]
main: me.fatpigsarefat.skills.PlayerSkills
softdepend: [Citizens]
commands:
  skills:
    description: View skills
    usage: /skills
    aliases: [skill]
  skillsadmin:
    description: Skills admin
    usage: /skillsadmin
    aliases: [skilladmin]